### PR TITLE
Make push and perform_async return connection errors

### PR DESCRIPTION
**Pull request by cjbottaro**
@smn Can you take a look at this and confirm it's the functionality you want? If so, I'll shore up the test and fix documentation, changelog, etc.

### CODE REVIEW

**Comment by smn** [comment]
@cjbottaro yeah I think this covers it. Thank you!

**Comment by smn** [comment]
@cjbottaro any chances of getting these things merged in?

**Comment by smn** [comment]
This not being in the main release is why we're still running off of a fork. Would be great if we can get this merged in a release that's on hex.pm, let me know if I can help.

**Comment by cjbottaro** [comment]
Closing this because it's was incorporated into 1.0 elsewhere and going to accept @smn's PR for this functionality into 0.8.

**Pull request closed without merging**
