### PR TITLE
v0.6.0

### PR DESCRIPTION
**Pull request by cjbottaro**
Addresses
* #27
* #24
* #23
* #28 
* #30

### CODE REVIEW

**Comment by john-griffin** [comment]
On master we are seeing some failed jobs that are not getting retried, could this be due to not sending the FAIL command to faktory?

**Comment by john-griffin** [comment]
It appears the executor genserver sometimes crashes and calls `report_fail` (which logs ✘). These jobs are never retried and never persisted anywhere.

**Comment by cjbottaro** [comment]
That seems like a bug with Faktory then:
https://github.com/contribsys/faktory/wiki/Job-Errors#do-worker-crashes-trigger-retries

Also see this:
https://github.com/contribsys/faktory/wiki/Worker-Lifecycle#executing-jobs

It basically says if a worker doesn't ACK or FAIL a job within the reservation limit, then it is put back on the queue.

So the only way to lose jobs is if the worker accidentally ACKs the job without processing it.

Lastly, could you try `v0.6.0`? It's a pretty big rewrite which massively simplifies a lot of things.

If you choose to give `v0.6.0` a try, please note that configuration has changed (again) and it's basically exactly the same as configuring an Ecto repo (I figured it best to just follow an established pattern). See the module docs on how to configure:
* https://github.com/cjbottaro/faktory_worker_ex/blob/v0.6.0/lib/faktory/worker.ex
* https://github.com/cjbottaro/faktory_worker_ex/blob/v0.6.0/lib/faktory/client.ex

**Comment by emhagman** [comment]
@cjbottaro Is there any progress on this? I see there was a v0.7.0 branch created as well.

**Comment by cjbottaro** [comment]
This branch has been superseded by 0.7.0.

**Pull request closed without merging**
