### PR TITLE
Protocol.push failures are ignored

### PR DESCRIPTION
**Pull request by smn**
`perform_async/1` will return a job response when Faktory is offline. 

This makes it difficult for applications to give guarantees around handover of responsibility.

This is a breaking change since it forces an `{:ok, job}` and `{:error, reason}` response for `perform_async/1`.

Happy to continue work on this until it's fixed as this caused us to lose some production data. Submitting a PR with the work in progress so far to get a conversation going.

### CODE REVIEW

**Comment by smn** [comment]
@cjbottaro apologies for the formatting changes that are unrelated to this PR, it's mix format automatically doing its thing.

**Comment by smn** [comment]
We're running off of our fork atm while waiting for input on this PR @cjbottaro

**Comment by smn** [comment]
@cjbottaro any thoughts on getting this merged in?

**Comment by cjbottaro** [comment]
Shoot, sorry I didn’t see this.   
  

  
I’ll try to get it in this weekend. Also time to cut a release for 0.8.0.   
  

  
  

  
  
>

**Pull request merged**
